### ISSUE TITLE
Possible Bug in townhall selection?

### ISSUE THREAD

**Issue by Steve132** [Dentosal/python-sc2#116]
https://github.com/Dentosal/python-sc2/blob/bf4b85deadb826f3ecf23d5f614ec60cd1872f45/sc2/bot_ai.py#L107

If you are already at lair tech this line seems like it would prevent you from expanding.  Your first townhall is a lair now, but obviously 'build lair' is an invalid command for a drone when you go to expand.  Seems like a possible bug worth looking into?

**Comment by BurnySc2** [comment]
I saw that yesterday too and fixed it in https://github.com/Dentosal/python-sc2/commit/b19e210ded998b0b2bd6be17d56b51111c76d8bc , thanks though! =)
Will be merged to master branch in a couple days.

**Comment by Steve132** [comment]
if unit is None or self.can_afford(building): 
               error

Don't you mean `not can_afford()"

It seems weird to error if you can afford it.

**Comment by BurnySc2** [comment]
Yeah, I corrected it a few commits later.

**Comment by BurnySc2** [comment]
It should be fixed now and on master branch. If you still encounter issues, feel free to reopen this issue.
