### ISSUE TITLE
How can a bot quit the game?

### ISSUE THREAD

**Issue by yt4766269** [Dentosal/python-sc2#13]
I'm writing sc2 AI scripts with python-sc2 but I don't know how to let the bot quit the game.
Is there anyway of doing that?

**Comment by Dentosal** [comment]
Hi! Currently there is nice way to do this, but I'll add that later. Until that calling `self._client.leave()` can probably be used  for that in the BotAI.

**Comment by yt4766269** [comment]
I'm currently using version 0.3.1 on my computer. when I called self._client.leave(), I can leave the game but a error occurred:
![image](https://user-images.githubusercontent.com/13883222/35425134-844ea332-0293-11e8-93ee-b0fd8aa3a482.png)

**Comment by Dentosal** [comment]
Reproduced. Working on this now.

**Comment by Dentosal** [comment]
The bug is now fixed (in version 0.4.6), and calling `self._client.leave()` in a bot now properly resigns and quits the game.
