### ISSUE TITLE
How does a high-templar issue a psi-storm to attack a group of units

### ISSUE THREAD

**Issue by ericbroda** [Dentosal/python-sc2#130]
Assuming the upgrade has been successfully  researched, is there an example that shows how a templar can issue a psi-storm to attack a group of units?

**Comment by ryanthompson591** [comment]
Took me a while to figure out.  The important thing to remember is that the second parameter cannot be a unit but it must be a location.

		for high_templar in self.units(HIGHTEMPLAR):
			abilities = await self.get_available_abilities(high_templar)
			if PSISTORM_PSISTORM in abilities:
				#I don't storm anybody else, when I think about you I storm myself
				await self.do(high_templar(PSISTORM_PSISTORM, high_templar.position))

What you want to do instead of storming yourself is to find the center of the units you want to storm and then storm there.

**Comment by BurnySc2** [comment]
Using @ryanthompson591 solution should work. Additionally a check without querying the API would be to check if the unit has >= 75 energy. 
`if high_templar.energy >= 75:`
Closing this as the author did not reply for some time.
