### ISSUE TITLE
How to determine if an enemy can see a cloaked unit

### ISSUE THREAD

**Issue by ericbroda** [Dentosal/python-sc2#149]
I am successfully using DarkTemplar cloak ability, however, there are units that can make the unit visible.  Is there a way to determine if a cloaked unit is visible to an enemy?

I tried the "cloak" status and I can see my DarkTemplar is cloaked, however, "is_visible" and "is_blip" functions do not seem to provide the required capabilities.  Is there a function that provide this?

**Comment by nizarion** [comment]
The game does **not** inform you if your unit is visible or invisible. The way a human knows that his unit is visible is:

1. Enemy offensive units attack automatically if in range.
2. Your unit is within range of an enemy unit's "**Detector**" feature. While these units are known the one detecting may not be visible to you (e.g. protoss observer is cloaked).

It is not a matter of functions, it's within the game strategy that you may not know that your unit is visible.

**Extra**: When invisible, cloaked and moving burrowed units may be tracked by their slight "rippling" distortions. Invisible units retain their collision radius; their position may be given away if visible units must move around an invisible one. Detectors are still needed to target invisible units even if they are found these ways.

Source: [http://starcraft.wikia.com/wiki/Cloaking](url)
