### ISSUE TITLE
Any thing wrong with NEOSTEELFRAME upgrade for terran ?

### ISSUE THREAD

**Issue by beni-Lx** [Dentosal/python-sc2#153]
I was trying to get NEOSTEELFRAME upgrade from ENGINEERINGBAY building but i get this error that said ' 10 is not a valid upgrade id ' .
I looked in upgrade_id.py and found out 'NEOSTEELFRAME = 153 ' ! I comment it out and place : NEOSTEELFRAME = 10 instead and problem solved . is this a bug or im doing something wrong ?

**Comment by BurnySc2** [comment]
Yeah there was an issue about it.
Please use https://github.com/Dentosal/python-sc2/wiki/FAQ#the-pip-version-seems-to-be-outdated-how-do-i-install-the-version-from-github 
if you do not want to wait for an upgrade on the pip version.
