### ISSUE TITLE
Pending upgrades function returns incorrect information

### ISSUE THREAD

**Issue by ericbroda** [Dentosal/python-sc2#159]
bot.already_pending_upgrade returns incorrect information:  For example, when querying if UpgradeId.PROTOSSAIRARMORSLEVEL1 is pending, and answer between 0 and 1 is returned (when it is actually pending).  However, querying UpgradeId.PROTOSSAIRARMORSLEVEL2 (note LEVEL is 2) also shows as it as pending with the exact same return value despite only LEVEL-1 being researched.   I believe this occurs since each of these upgrades are dependant upon the same ability and the already_pending_upgrade code only checks to match the ability ID.

Rather, the code should look for ability ID match and ALSO determine f previous upgrade has been completed.

**Comment by tweakimp** [comment]
Can confirm.
I am working on it.

**Comment by BurnySc2** [comment]
Fixed on develop branch, will be merged to master branch soon™
