### ISSUE TITLE
Attack move for group of units

### ISSUE THREAD

**Issue by thefirebanks** [Dentosal/python-sc2#161]
Hey there! 

I noticed that the Unit class is the one that has the attack() method, yet I was wondering if the feature of making a group of units attack a specific spot/units was implemented yet? So far I've been just looping through the units in the group and making them attack the same target, but that involves selecting each one of them and then implementing the command rather than the whole group:

```python
   async def on_step(self, iteration):
        for u in self.units.idle:
            await self.do(u.attack(self.find_target()))
```

Is there a way of doing:

```python
   async def on_step(self, iteration):
        group = select_group_from(self.units.idle)
        await self.do(group.attack(self.find_target()))

```

I think that this would be useful for control groups and joint targets... but correct me if I'm wrong/doesn't make a difference. Thanks!

**Comment by jaros3** [comment]
Use the following snippet:
```
async def on_step (self, iteration):
    await self.doMany ([unit.attack (target) for unit in self.units.idle])

async def doMany (self, actions: List[UnitCommand]):
    r = await self._client.actions (actions, game_data = self._game_data)
    if r:
        print (f'Error: {r} (action = {actions[0]})');
    return r
```
The trick here is to group multiple commands into a batch before sending to server. The commands are grouped so long as it's the same ability, same target and same queue/noqueue flag. This works for group attack just fine.

**Comment by thefirebanks** [comment]
This works, thank you!!
