### ISSUE TITLE
Add convenience method to redistribute workers

### ISSUE THREAD

**Issue by reypader** [Dentosal/python-sc2#19]
We can re-structure the output of `BotAI.expansion_locations` to become a dictionary of a rounded Point2D with resource groups instead of just a list of rounded Point2D. This, alongside a convenience method to get owned expansions would allow us to potentially get nearby workers, compare them with the amount of resource nodes, and redistribute.

EDIT:
I just found out there's a `assigned_harvesters` and `ideal_harvesters` property on units. I presume these are for the townhall and extractors. Instead of counting the nodes, we can use these instead. Though, turning the expansions into dictionaries could still be useful. I reckon when someone manages to make a script to drop into the enemy mineral line, they'd prioritze attacking expansions with more nodes.

**Comment by Dentosal** [comment]
> I just found out there's a assigned_harvesters and ideal_harvesters property on units. I presume these are for the townhall and extractors.

Correct.

> I reckon when someone manages to make a script to drop into the enemy mineral line, they'd prioritze attacking expansions with more nodes.

Most likely this, or just the expansion with more workers.

**Comment by reypader** [comment]
I've updated the PR to incorporate recent changes in `BotAI.on_step`.
