### ISSUE TITLE
How do I determine what building can train each unit?

### ISSUE THREAD

**Issue by JuhaniGeniem** [Dentosal/python-sc2#194]
How to select the correct building when all I know is the bot wants to build `ZEALOT` and or `PROBE`?

I don't want to create a huge `if else` chain to be able to build all units.

Here's a pseudo example:
```
unit = ZEALOT

building_type = get_unit_building_type(unit) <-- How to do this?

building = get_single_building(building_type)

self.do(building.train(unit))
```

**Comment by ceacar** [comment]
as a beginner,
here is a way i can think of

buildable = {
"gateway": [ZEALOTS, STALKER, ...],
...
}

**Comment by tweakimp** [comment]
You can query the buildings abilities with get_available_abilities from bot_ai.py

**Comment by tweakimp** [comment]
Note that these queries can take a long time, its probably best to save the result for each building type and only redo the query some tech requirement finished.
I think this is solved then, feel free to reopen if there is something else.
