### ISSUE TITLE
Please add radius info into EffectData

### ISSUE THREAD

**Issue by Matuiss2** [Dentosal/python-sc2#216]
The protocol has that information:
https://github.com/Blizzard/s2client-proto/blob/9906df71d6909511907d8419b33acc1a3bd51ec0/s2clientprotocol/data.proto#L119

But this API doesn't, it just has the id and the positions(which just returns the center):
https://github.com/Dentosal/python-sc2/blob/f96217b29a928d5fe064cf393c2bf63a405e3344/sc2/game_state.py#L73

**Comment by tweakimp** [comment]
You linked the game data, but we are getting the event in the game from the observeation response. And that does not have the radius. https://github.com/Blizzard/s2client-proto/blob/9906df71d6909511907d8419b33acc1a3bd51ec0/s2clientprotocol/raw.proto#L142

I will try to get the radius from the game data.

**Comment by tweakimp** [comment]
Done :)

**Comment by Matuiss2** [comment]
nice! thanks
