### ISSUE TITLE
Logger gives an error for human players

### ISSUE THREAD

**Issue by drakonnan1st** [Dentosal/python-sc2#223]
line 199 in main.py:
`    logging.info(f"Result for player {player_id} ({player.ai.__class__.__name__}): {result._name_}")`
If one of the players is human, then once the game ends, we get this error:
`AttributeError: 'Human' object has no attribute 'ai'`

Possible fix that still displays Bot's class name:
```
    typestring = player.ai.__class__.__name__ if isinstance(player, Bot) else player
    logging.info(f"Result for player {player_id} ({typestring}): {result._name_}")
```

**Comment by tweakimp** [comment]
Should be fixed now
