### ISSUE TITLE
Prevent action if unit already has that action

### ISSUE THREAD

**Issue by tweakimp** [Dentosal/python-sc2#249]
Many python bots suffer from sending the same action many times, for example if an army is sent over the map and gets the same attack command every frame.

We should filter out unnecessary commands in `do_actions` or `combine_actions`

**Comment by mindme333** [comment]
This is something I personally do within my own bot.

**Comment by Lambdanaut** [comment]
So if the order_target corresponds to the new action, just don't do the new action?

**Comment by tweakimp** [comment]
the action has to be the same,too
in your example, if you attack a point and then move to that point, you wouldnt do the move

**Comment by Lambdanaut** [comment]
okay, makes sense. 
I think if we do this we should add a flag to `force_action` in case there is some edge case.

**Comment by tweakimp** [comment]
Do you think the single actions should have this option or the do_actions function? That means: do you want to force every action for that do_actions call or only specific actions?

**Comment by Lambdanaut** [comment]
I think it makes sense to change both of them, if it's not too much work.

**Comment by tweakimp** [comment]
Fixed in https://github.com/Dentosal/python-sc2/pull/252
