### ISSUE TITLE
Evolution Chamber not upgrading Ground Carapace

### ISSUE THREAD

**Issue by phytobacter** [Dentosal/python-sc2#254]
async def upgrade_evolutionchamber(self):
		if self.units(EVOLUTIONCHAMBER).ready.exists:
			for chamber in self.units(EVOLUTIONCHAMBER).ready:
				abilities = await self.get_available_abilities(chamber)
				# WORKS!
				if AbilityId.RESEARCH_ZERGMISSILEWEAPONSLEVEL1 in abilities:
					if self.can_afford(AbilityId.RESEARCH_ZERGMISSILEWEAPONSLEVEL1):
						await self.do(chamber(AbilityId.RESEARCH_ZERGMISSILEWEAPONSLEVEL1))
				
				# AttributeError: RESEARCH_ZERGGROUNDARMORSLEVEL1
				if AbilityId.RESEARCH_ZERGGROUNDARMORSLEVEL1 in abilities:
					if self.can_afford(AbilityId.RESEARCH_ZERGGROUNDARMORSLEVEL1):
						await self.do(chamber(AbilityId.RESEARCH_ZERGGROUNDARMORSLEVEL1))

Hello all!

I have been struggling in trying to get the evolution chamber to research Ground Carapace Level 1. In the sc2.ids.upgrade_id, this is defined as ZERGGROUNDARMORSLEVEL1. 

I tried it with ZERGMISSILEWEAPONSLEVEL1 and it worked, so I'm confused why it would not work on ZERGGROUNDARMORSLEVEL1. The error it returns is: AttributeError: RESEARCH_ZERGGROUNDARMORSLEVEL1.

Above is my attached code for reference.

**Comment by Matuiss2** [comment]
ok, you probably figured it out already but its `RESEARCH_ZERGGROUNDARMORLEVEL1` not `RESEARCH_ZERGGROUNDARMORSLEVEL1`.

**Comment by phytobacter** [comment]
Oh, you're right! Thanks! It works as it should now!
