### ISSUE TITLE
Critical error... "icuuc52.dll" does not exist.

### ISSUE THREAD

**Issue by ExileBit** [Dentosal/python-sc2#258]
When I try running the code I always stumble accros "Critical error during loading process. Required library "icuuc52.dll" does not exist." 

I´ve already tried to repair/reinstall the game, put the dll in Starcraft´s Support and Support 64 folder, add the dll to the computer path, but nothing seems to work.

I hope somebody knows the answer.

**Comment by ExileBit** [comment]
If anyone has the same problem and is using PyCharm 2019.01 downgrading to PyCharm 2018.03 will help

**Comment by Snoup97** [comment]
Not using PyCharm 2019.1 did it for me Thanks M8 <3

**Comment by Zamiell** [comment]
I also ran into this issue, but with a JavaScript client, not Python.

For anyone else running into this issue, I found that the solution was that I did not have the Battle.net launcher open.
Once I had it open (and authenticated), then I was able to boot SC2 just fine from my code.
