### ISSUE TITLE
The `has_add_on` documentation is misleading or implementation is reverse

### ISSUE THREAD

**Issue by Saloshp** [Dentosal/python-sc2#259]
The documentation says:
> has_add_on | bool if add_on_tag == 0

Testing unit.has_add_on returns False for structures with add_ons

**Comment by tweakimp** [comment]
This is fixed in the dev branch but not yet merged.
See https://github.com/Dentosal/python-sc2/blob/develop/sc2/unit.py#L597

I also corrected the wiki entry.
