### ISSUE TITLE
Use `stableid.json` to generate ID enums

### ISSUE THREAD

**Issue by reypader** [Dentosal/python-sc2#26]
The `sc2_typeenums.h` in sc2client-api doesn't seem to contain all of the currently available abilities. This could potentially make sure that we always have the complete ID. However, this would make using the enums as globals impossible because some abilities have the same name as units. This is particularly true for build and train abilities.

see https://github.com/Dentosal/python-sc2/pull/24

**Comment by reypader** [comment]
I think I stumbled across how the sc2client-api named their enums. It looks like `use friendlyname if available, otherwise use name_buttonname`.

Using that naming standard lead to everything in the core sc2 API working as-is.

**Comment by Dentosal** [comment]
Apparently some names are still broken. For example, `EFFECT_` prefix is now required. However this seems good enough, so I have updated the broken examples to support this new naming.
