### ISSUE TITLE
TypeError in distribute_workers

### ISSUE THREAD

**Issue by B204L** [Dentosal/python-sc2#280]
Using the latest `develop` branch and forking the template for [overmind-challenge](https://gitlab.com/overmind-challenge/overmind-challenge-template) and using the same folder / file structure. I am using the `run_locally.py` script in the root folder for testing, my bot files are inside the `bot` directory and I'm using the default `MyBot` class.

`Traceback (most recent call last):`

  `File "C:\Program Files (x86)\Python37-32\lib\site-packages\sc2\main.py", line 166, in _play_game_ai
    await ai.on_step(iteration)`

  `File "C:\Users\justin\Documents\sc2ai\overmind-challenge\bot\main.py", line 50, in on_step
    await self.distribute_workers(self)`

  `File "C:\Program Files (x86)\Python37-32\lib\site-packages\sc2\bot_ai.py", line 357, in distribute_workers
    if self.vespene and self.minerals / self.vespene < resource_ratio:`

`TypeError: '<' not supported between instances of 'float' and 'MyBot'`

`ERROR:sc2.main:Error: '<' not supported between instances of 'float' and 'MyBot'`

I am using `await self.distribute_workers(self)` in the `on_step`, TypeError occurs momentarily after geysers are built.

Python 3.7.3

**Comment by BurnySc2** [comment]
In `self.distribute_workers(self)` it appears you pass in your bot object as a function argument. 

Instead, you should pass in a number, e.g.
`await self.distribute_workers(resource_ratio=2)`
or just leave it empty `await self.distribute_workers()`

**Comment by B204L** [comment]
Thanks, will do in the future.
