### ISSUE TITLE
Is it possible to visualize the distance in sc2?

### ISSUE THREAD

**Issue by baibinghere** [Dentosal/python-sc2#296]
I'm writing code to micro control marines to fight, but it's hard for me to grap the concept of distance inside sc2. Is there any tools or functions to help me visualize the distance?
If this topic is not valid for the project, please close it. thanks.

**Comment by UltraMachine** [comment]
use methods from client.py
```python
async def on_step(self):
    self._client.debug_line_out(position1, position2, color)
    await self._client.send_debug()
```

**Comment by baibinghere** [comment]
@UltraMachine cool, it works! 
Great help! thanks!
