### ISSUE TITLE
Is it possible to snapshot a game state?

### ISSUE THREAD

**Issue by baibinghere** [Dentosal/python-sc2#297]
Some scenarios needs to take a long time to reproduce.
I'm wondering if there's a way to take a snapshot of the game state, like <save game>.
E.g.
```python
def step(self):
    if iteration == 2847:
        self.save_game_state()
```

Then when we want to reproduce, we can simply restore the game state.

**Comment by danielvschoor** [comment]
Hi. You might want to join the discord where there are more people to help you with any questions you might have: https://discordapp.com/invite/Emm5Ztz
