### ISSUE TITLE
Detect expansion locations

### ISSUE THREAD

**Issue by Dentosal** [Dentosal/python-sc2#3]

**Comment by Dentosal** [comment]
Partially implemented in 4fe7734

**Comment by reypader** [comment]
I've added a PR to enhance expansion detection and placement. Please see https://github.com/Dentosal/python-sc2/pull/17. I've tested it in Abyssal Reef and all of the expansions were taken and the placement was flush with the resource nodes.

**Comment by Dentosal** [comment]
Thank you for the PR. I reviewed it, and it looks great. Merged.
