### ISSUE TITLE
Add/document support for tracking action failures

### ISSUE THREAD

**Issue by hsalokor** [Dentosal/python-sc2#31]
Currently there seems to be no way to track if the action actually succeeds. This makes it possible for the bot to continue repeating actions that will continuously fail.

One way to handle this would be to allow passing a optional `on_error` callback to `self.do(...)` function. This would allow easier debugging for cases when you continuously fail to apply an upgrade to building, for example.

**Comment by Dentosal** [comment]
Error can be received from `self.do` like this:

```python
error = await self.do(ACTION)
```

However, it the error is received after the call (e.g. building is blocked by enemy unit), it is not currently  easy to detect. Moreover, linking that to `self.do` call isn't really possible.

**Comment by BurnySc2** [comment]
Action errors should be available now on the next step call, directly from the Blizzard SC2 API https://github.com/Dentosal/python-sc2/commit/6815043c1d6c1b69fcc094bf5db1177bf48ee66c
Accessable in step function via `self.state.action_errors` (untranslated for now, this may change)
This is especially useful if you use `self.do_actions()` like implemented here https://github.com/Dentosal/python-sc2/commit/12b2ae7fea8e7e3e57ffccc27df33550ced2bbd1
