### ISSUE TITLE
Simplify unit management by supporting trackable groups

### ISSUE THREAD

**Issue by hsalokor** [Dentosal/python-sc2#32]
Currently the API supports picking closest units. It would be beneficial to allow explicit grouping of units, since often they tend to wander off. if you increase your pick distances, it becomes more likely that you pick up "wrong" units.

One way to support this is to use `unit.tag`. One could quite easily add `on_step` that would process all units (using sets), and check all the given groups for casualties and other trivia ("group under attack"). This would allow tracking multiple groups of units, and moving reinforcements between them.

**Comment by Dentosal** [comment]
Control groups are now implemented (published in version 0.7.1). See [`examples/proxy_rax`](https://github.com/Dentosal/python-sc2/blob/master/examples/proxy_rax.py) for example usage. They are still missing some functionality (like easily moving units between groups).

**Comment by Dentosal** [comment]
Added more functionality to control groups in  03430a5 (version 0.7.2). Feel free to reopen if something is missing.
