### ISSUE TITLE
run_game() without closing process?

### ISSUE THREAD

**Issue by Xeizzen** [Dentosal/python-sc2#40]
Is it possible to leave the process opened after bot finished it's executing?
Asking for that because it would help to reduce the time it takes for the bot to launch for the second time, because otherwise we have to wait for the game process to be relaunched after we launch the bot.
Yes, leaving inactive process takes memory but it would greatly help in terms of development and debugging speed.

**Comment by Dentosal** [comment]
Do you mean using `RequestRestartGame` to restart the game after it's completed?

**Comment by Xeizzen** [comment]
I mean leave the process opened in "stand-by" mode, listen to some port and wait for further connections.
You can do that by issuing this set of commands in the shell (your paths may vary):
```
cd \path\to\StarCraft II\Support64\
"\path\to\StarCraft II\Versions\Base65384\SC2_x64.exe" -listen 127.0.0.1 -port 8000 -displayMode 0
```
By issuing these commands we will have an open inactive process of starcraft 2 listening for the incoming connections at the port of 8000.

**Comment by Dentosal** [comment]
Can you do that? Is it possible to start a second game without relaunching?

**Comment by Xeizzen** [comment]
Yes, it was possible for me 6 months ago with sc2client-protocol written on python, and I tried to make modifications to make it possible on pysc2 too.

**Comment by Dentosal** [comment]
I tested this, and it works. Planning to release this with the next version, later this week probably.
