### ISSUE TITLE
The way to get a pointer on a unit currently in production?

### ISSUE THREAD

**Issue by Xeizzen** [Dentosal/python-sc2#42]
Is there any way to get a pointer to a unit after we ordered its production?
This is would come in handy for a zerg players, after they'll order to morph a unit from a larva.

**Comment by Dentosal** [comment]
Unit's `tag` is persistent, and it is preserved over game loops and unit transitions. When larva is trained to a unit, the tag is still the same. So you can take `larva.tag` when training it, and later use `self.units.by_tag(larva_tag)` to find it. This doesn't work for zerglings, as they are created in pairs. It seems to me that both lings get their own new tag.
