### ISSUE TITLE
"int" object is not iterable exception at PixelMap object

### ISSUE THREAD

**Issue by Xeizzen** [Dentosal/python-sc2#43]
While trying to get access to the "print" method of PixelMap object I got TypeError exception: 'int' object is not iterable.

More specifically, I tried to print pathing_grid object stored as an attribute of "_game_info" object of sc2.BotAI class.

The line traceback is pointing at:
https://github.com/Dentosal/python-sc2/blob/d2437ab928e359497688e84d499f48c77f8f3bfa/sc2/pixel_map.py#L57

**Comment by Dentosal** [comment]
Reproduced. Non-critical. Fix is trivial, and will be included into next version.

**Comment by Dentosal** [comment]
Fixed in version `0.8.0`.
