### ISSUE TITLE
Add endpoint for checking what upgrades are currently researched

### ISSUE THREAD

**Issue by Dentosal** [Dentosal/python-sc2#46]

**Comment by BurnySc2** [comment]
I added an endpoint for that in my fork (see pull request).
Usable in the step event with
```python
# from sc2.ids.upgrade_id import UpgradeId
example_upgrade = UpgradeId.STIMPACK
if example_upgrade in self.state.upgrades:
    # do stuff because upgrade is finished
```

**Comment by BurnySc2** [comment]
Added as a function called `already_pending_upgrade(UpgradeId)` - included in the `already_pending` function since commit https://github.com/Dentosal/python-sc2/commit/115895eecae57fb0c29dfa5fecb6f90933e96a13
