### ISSUE TITLE
Use ExecuteInfo.txt

### ISSUE THREAD

**Issue by Archiatrus** [Dentosal/python-sc2#50]
If python-sc2 would use `C:\Users\<username>\Documents\StarCraft II\ExecuteInfo.txt` instead of a hard-coded path it could easily support non-standard installation paths. I assume there is also a ExecuteInfo.txt for mac.

Regards

**Comment by EmberQuill** [comment]
On Mac you should be able to find the same file at `~/Library/Application Support/Blizzard/StarCraft II/ExecuteInfo.txt`.

**Comment by Dentosal** [comment]
Is this documented anywhere? How does this relate to data files? Or is this just the executable path?

**Comment by Archiatrus** [comment]
It is the path to the latest started executable. And I think it is used to find it in the c++ api: https://github.com/Blizzard/s2client-api/blob/c577c9c480ad430d86e736012a00cdf1db62dbf3/src/sc2api/sc2_args.cc#L13

**Comment by Dentosal** [comment]
Looks like we should probably use this, then.

**Comment by Cryptyc** [comment]
This is becoming an increasing problem for ladder bots at the moment, would be really good if this was a priority :)

**Comment by BurnySc2** [comment]
AiSee took care of it, this should be working on windows now (untested on mac): https://github.com/Dentosal/python-sc2/commit/647e53a51d79d06f257af06570896499f064e070
Will merge it to master branch soon™
