### ISSUE TITLE
Can not install python-sc2 BUT pysc2...

### ISSUE THREAD

**Issue by ero91** [Dentosal/python-sc2#51]
In Cmd: Collecting python-sc2
Error: Could not find a version that satisfies the requirement python-sc2 (from versions: )
No matching distribution found for python-sc2

So I extracted the folder "sc2" manually...could this be the reason?

**Comment by BurnySc2** [comment]
I think you have used the wrong command. You need to use 
`pip3 install --user --upgrade sc2`

Maybe this video can get you started: https://www.youtube.com/watch?v=v3LJ6VvpfgI

**Comment by m1ndgames** [comment]
correct, python-sc2 needs python >3.6.

on most systems the command "python" will run python version 2, while python3 (pip3 respectively) runs python version 3.

**Comment by XxGruffuddxX** [comment]
I keep getting a syntax error every time I run the command in python. I even tried to copy and past your code into python.
