### ISSUE TITLE
Running a game with two bots in real-time mode.

### ISSUE THREAD

**Issue by daniel-kukiela** [Dentosal/python-sc2#54]
Hi,

I'm trying to run a game with two bots in real-time mode, but it looks like it doesn't register end of the game.
If i run bot vs computer both in real-time and in not real-time mode, or bot vs bot in not real-time mode, it works, but not when running bot vs bot in real-time.
Do anyone know a solution for that?

I was trying to debug that problem and it looks like response object:
`response.ParseFromString(response_bytes)`
doesn't contain `player_result`

Example from non-real-time mode:
```
  player_result {
    player_id: 1
    result: Victory
  }
  player_result {
    player_id: 2
    result: Defeat
  }
```

**Comment by Dentosal** [comment]
This is an issue in the protocol level, and it's we cannot fix it in the library easily. I opened issue in the protocol repo more than a year ago: https://github.com/Blizzard/s2client-proto/issues/90
