### ISSUE TITLE
Importing problem with pycharm

### ISSUE THREAD

**Issue by GloryToArstotzka** [Dentosal/python-sc2#55]
I pip installed the SC2 , and now in pycharm and I can import it , I can also import sc2.player , but I can't do "from sc2.constants import PROBE" , is there a fix?

**Comment by DevJhns** [comment]
@GloryToArstotzka  yeah make import * (means import all),
you will see red alerts, but still it works

**Comment by mjschuetze102** [comment]
You can "Ignore unresolved reference 'constants.PROBE'". It will still run even though it says it can't find it. Also the red underline will go away.

**Comment by GloryToArstotzka** [comment]
you are right , thanks

**Comment by postcert** [comment]
If you'd like to not ignore the warnings and have code completion.
Import like:
`from sc2.ids.unit_typeid import UnitTypeId`
and access the Enums like
`nexus = self.units(UnitTypeId.NEXUS).first`
