### ISSUE TITLE
How to use the bot against regular players

### ISSUE THREAD

**Issue by GloryToArstotzka** [Dentosal/python-sc2#56]
In the docs theres nothing talking about that , so after hours of searching in files I couldn't find a way to make the bot play with regular players, how to do it?

**Comment by BurnySc2** [comment]
Check out [this example](https://github.com/Dentosal/python-sc2/blob/master/examples/play_tvz.py) from this library.

You just have to change
```python
Bot(Race.Zerg, ZergRushBot()),
Computer(Race.Terran, Difficulty.Medium)
```
to
```python
Human(Race.Terran),
Bot(Race.Zerg, ZergRushBot())
```
at the end of the file to be able to play as human/player against bot/computer.

**Comment by GloryToArstotzka** [comment]
I know how to play with my own bot , but is there a way to make a bot fight a player in matchmaking or a friend who I ask to instead of just me?

**Comment by mjschuetze102** [comment]
Unless you give them the code and have them run it I don't believe so. If I'm not mistaken, the code is running in an offline version of the game. Even if you were to make in run in an online version, I'm sure you'd be breaking some rule in Blizzard's terms for online match making

**Comment by GloryToArstotzka** [comment]
there should be a way to create a custom game , where people can play against the bot without them to get the code
