### ISSUE TITLE
Access to any time reference?

### ISSUE THREAD

**Issue by davidgsteadman** [Dentosal/python-sc2#57]
I've not seen a reliable way to measure the passage of game-time. The passing of iterations varies greatly between realtime true/false modes, and the numbers I need also differ from the sentdex tutorial. 

Is there any way to access that game-clock near the bottom left of the screen?

Thanks.

**Comment by davidgsteadman** [comment]
Now having seen: https://github.com/Dentosal/python-sc2/issues/29#issuecomment-365874073

self.state.game_loop increments around 22.5 per game-clock-second across both Realtime and non-realtime modes.

**Comment by Archiatrus** [comment]
Just to be exact (could be relevant to your application): it is 22.4 steps per second. Normal speed is 16 steps per second and faster (the default speed) means 1.4 times faster.
