### ISSUE TITLE
VScode "from sc2.constants import *" not working 

### ISSUE THREAD

**Issue by momo-iah** [Dentosal/python-sc2#58]
VScode "from sc2.constants import *" not working, and i have below error massage
E0602:Undefined variable 'PROBE'

Also, I tried:

from sc2.constants import PROBE
[pylint] E0611:No name 'PROBE' in module 'sc2.constants'

**Comment by mjschuetze102** [comment]
Add UnitTypeId. in front of probe: UnitTypeId.PROBE

**Comment by HayaiAlex** [comment]
I have the same error and tried your fix but get the error.
E0001:invalid syntax (<unknown>, line 4)

**Comment by HeNKiEeEeE** [comment]
Does not solve the issue.

**Comment by BurnySc2** [comment]
Use the fix suggested by @HeNKiEeEeE 
```python
from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.ability_id import AbilityId
from sc2.ids.buff_id import BuffId
from sc2.ids.upgrade_id import UpgradeId
from sc2.ids.effect_id import EffectId
```
I have this at the top of each of my files. Autocomplete works for me in VScode and Pycharm with this.
