### ISSUE TITLE
AttributeError: 'ControlGroup' object has no attribute 'amount'

### ISSUE THREAD

**Issue by oxrock** [Dentosal/python-sc2#62]
error I get when calling if self.scoutGroup.empty()

basically checking if my scout is alive or not and it throws this error. ControlGroup was initialized without error.

**Comment by BurnySc2** [comment]
Yep, this has to be
```python
@property
def empty(self):
    return len(self) == 0
```

**Comment by BurnySc2** [comment]
Will be fixed in https://github.com/Dentosal/python-sc2/commit/38db7c29b1a2169abbf86f440f00f600d0fb9e3b
