### ISSUE TITLE
Can not find_placement for Stalker Blink

### ISSUE THREAD

**Issue by mjschuetze102** [Dentosal/python-sc2#64]
I'm trying to get the Stalker to use the blink ability. Unfortunately, they don't always find a position to blink to. I find a position to try and blink to (pos) but it was not always working.

So I took the find_placement method from the WarpGate example for spawning stalkers and tried to have possible positions created from that, however the method is always returning None.

I would like for the Stalkers to "always" have a position to blink to, but I can't find a suitable function that will locate a position if find_placement will not work and pos is not a valid blink location.

```
if AbilityId.EFFECT_BLINK_STALKER in abilities:
    pos = s.position.to2.towards_with_random_angle(
                         self.units(UnitTypeId.NEXUS).closest_to(s).position)

    placement = await self.find_placement(AbilityId.EFFECT_BLINK_STALKER, pos,
                                          max_distance=8, placement_step=1)
    if placement is None:
         print("Stalker is not able to blink")

    await self.do(s(AbilityId.EFFECT_BLINK_STALKER, pos))
```

**Comment by DevJhns** [comment]
@mjschuetze102 
u can try something, like this

 pos = s.position.to2.random_on_distance(random.randrange(1, 8))

and if not mistaken, you should do 
await self.do(s(AbilityId.EFFECT_BLINK_STALKER, placement)) in last string

**Comment by mjschuetze102** [comment]
> pos = s.position.to2.random_on_distance(random.randrange(1, 8))

random.randrange doesn't exactly achieve what I'm trying to do... I'm trying to get stalker blink micro in combat to work, so I can't just pick a random spot to travel to.

> and if not mistaken, you should do
await self.do(s(AbilityId.EFFECT_BLINK_STALKER, placement)) in last string

Yes, but it throws an error since it's always returning None. However using pos, the stalker will sometimes be able to find a location

**Comment by BurnySc2** [comment]
If this is still not solved, you could look at how Hannessa approaches this problem:
https://github.com/Hannessa/sc2-bots/blob/master/cannon-lover/cannon_lover_bot.py#L561-L572
