### ISSUE TITLE
Inconsistent iterations rate: 30 iterations = 40 seconds?

### ISSUE THREAD

**Issue by alexander-kazakov** [Dentosal/python-sc2#66]
Hi guys,

Testing very simple bots against each other in realtime mode.

Issues:
1. Iteration 0 is called in the code at the ~1 minute 21 seconds of the game. 
And it is run at different times for each bots. Shouldn't it be run on the first second of the match?

https://i.imgur.com/nuFomNk.png

2. Once some attacking happens between the workers, the iterations stop ticking at regular intervals. And it can take ~40 seconds to count 30 iterations while normally 1 second contains ~30 iterations.

https://i.imgur.com/QWkUSBn.png
https://i.imgur.com/shcsjR7.png

This makes it impossible to code any reasonable bot strategy. For example it takes multiple minutes for defending bot workers to actually attack each of the invading workers. And there are 10-20 seconds gaps between one target is destroyed and the next target attack command is executed.

Have anyone experienced the same?

My Machine: MacOS 10.13.5, Python 3.6.5, Installed the SC2 client and Python API yesterday.

Source code:

` import sc2
from sc2 import run_game, maps, Race, Difficulty
from sc2.player import Bot, Computer

class DefendingBot(sc2.BotAI):
    async def on_step(self, iteration):
        if iteration == 0:
            await self.chat_send(f"I am a Defending Bot")
        if (iteration % 30 == 0): # Detection is run every few frames
            await self.chat_send(f"Iteration: {iteration}")
            await self.chat_send(f"Enemies detected: {self.known_enemy_units.amount}")
            if (self.known_enemy_units.amount > 0):
                for worker in self.workers:
                    await self.do(worker.attack(self.known_enemy_units.first))

class InvadingBot(sc2.BotAI):
    async def on_step(self, iteration):
        if iteration == 0: # If this is the first frame
            await self.chat_send(f"I am an Invading Bot")
            for worker in self.workers:
                # Send all workers to the other bot's location
                await self.do(worker.move(self.enemy_start_locations[0]))

run_game(maps.get("AbyssalReefLE"), [
    Bot(Race.Protoss, DefendingBot()),
    Bot(Race.Protoss, InvadingBot()),
], realtime=True) `

**Comment by mjschuetze102** [comment]
#29 This might be a bit better for you

**Comment by alexander-kazakov** [comment]
Thanks! If I understand the last comment of #29 right, in real-time mode the on_step calls can happen at any time, sometimes rarely, sometimes often. Depending on the computing power of the machine? So a slow machine is not suitable to see a meaningful bot play on a slow machine (as on_step may have delays of multiple seconds).

But in non-realtime mode the on_step calls should be consistently regular. And #29 explains how to get ~game time from the API.

Did I get it right?

**Comment by mjschuetze102** [comment]
I don't know if it's dependent on computing power or not, but yes, there is not a consistent way iterations to handle realTime= False. `self.state.game_loop` may be more suitable for what you are trying to do

**Comment by BurnySc2** [comment]
Similar questions: #57 and #29
