### ISSUE TITLE
position doesn't update

### ISSUE THREAD

**Issue by Garakros** [Dentosal/python-sc2#79]
.position parameter doesn't update I always get same value, no matter where unit is.

**Comment by Garakros** [comment]
I wanted my scout to build one pylon while moving towards enemy base like this:

async def scout_buildings(self):
    if self.have_scout:
        if self.can_afford(PYLON):
            await self.build(PYLON, near=self.my_scout.position, unit=self.my_scout)

And scout is created like this:

def create_scout(self):
    if self.iteration % 25 == 0 and self.have_scout is False:
        self.__class__.my_scout = self.units(PROBE).random
        self.have_scout = True
        print("Scout created")

Whenever async scout_buildings is run scout wants to return to base to create building (and I print location everytime and it's always the same. It looks like position saved is same as position from the start of the game.

**Comment by ryanmccauley211** [comment]
At each step the BotAI class calls the method _prepare_step() which gets the units from the new state. Your unit positions and other fields won't get updated and so the position won't change.

You can do this instead - self.units.find_by_tag(self.my_scout.tag).position to get the updated position.

**Comment by Garakros** [comment]
Yup if I do it like this it works. Thanks for answer.
