### ISSUE TITLE
Improve BotAI.already_pending 

### ISSUE THREAD

**Issue by Dentosal** [Dentosal/python-sc2#8]
* Count instances of this building already in progress
* Count workers currently moving to build the given building

**Comment by reypader** [comment]
I was able  to rework `BotAI.already_pending` in the build order support to instead return the count and rely on falsy/truthy values. I'll cherry-pick it and create a PR.

**Comment by reypader** [comment]
It might be good to also include support for upgrade detection in `already_pending`.

**Comment by reypader** [comment]
PR#21 has been fixed to return 0 when none of the conditions are met

**Comment by Dentosal** [comment]
Merged.
