### ISSUE TITLE
No game window shown while execution under ubuntu

### ISSUE THREAD

**Issue by houghstc** [Dentosal/python-sc2#80]
Hello,
I'm trying to run the examples under ubutun 16.04LTS, and it seems working but no game window shows. Does anyone have some ideas? Thank you.

Here are some log:

python3.6 examples/worker_rush.py 

Version: B60604 (SC2.4.01)
Build: May  1 2018 19:24:12
Command Line: '"/home/zhi/StarCraftII/Versions/Base60321/SC2_x64" -listen 127.0.0.1 -port 20923 -displayMode 0 -dataDir /home/zhi/StarCraftII -tempDir /tmp/SC2_sew1lzxd'
Starting up...
Startup Phase 1 complete
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:20923
Startup Phase 3 complete. Ready for commands.
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     AbyssalReefLE
INFO:sc2.controller:Players: Bot(Race.Zerg, <__main__.WorkerRushBot object at 0x7f3dd6d43518>), Computer(Race.Protoss, Difficulty.Medium)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
INFO:sc2.protocol:Client status changed to Status.in_game (was None)
INFO:root:Player id: 1

**Comment by Korczak** [comment]
Hello,
Have you solved this error? I have got the same issue.

**Comment by houghstc** [comment]
Hello,
from what i'm understanding, the blizzard's sc2 linux binary doesn't have a GUI, and neither does Dentosal's python-sc2 package. So it's normal that there is no GUI launched. But Deepmind's pysc2 indeed implements a easy version of GUI and that's what I see when executing their package.
