### ISSUE TITLE
How can you use Protoss Nexus ability Chrono Boost?

### ISSUE THREAD

**Issue by Garakros** [Dentosal/python-sc2#82]
I can't make Nexus cast Chrono Boost how do you do it? Is there some list of what you can use? I checked Wiki of this package and the best I could find is AbilityId.EFFECT_CHRONOBOOST. What I tried to do so far:

nexus = self.units(NEXUS).first

if self.workers.amount < 20 and nexus.noqueue:
    if self.can_afford(AbilityId.EFFECT_CHRONOBOOST):
        await self.do(nexus(AbilityId.EFFECT_CHRONOBOOST, nexus))

**Comment by ryanmccauley211** [comment]
I'm also having this problem. This is the request being sent:
action {
  actions {
    action_raw {
      unit_command {
        ability_id: 261
        target_unit_tag: 4346347521
        unit_tags: 4346347521
        queue_command: false
      }
    }
  }
}

and the response:

action {
  result: NotSupported
}
status: in_game

**Comment by mjschuetze102** [comment]
async def chronoboost(self):
        if self.units(PYLON).exists:
            for nexus in self.units(NEXUS):
                abilities = await self.get_available_abilities(nexus)
                if AbilityId.EFFECT_CHRONOBOOSTENERGYCOST in abilities:
                    if not nexus.has_buff(BuffId.CHRONOBOOSTENERGYCOST):
                        await self.do(nexus(AbilityId.EFFECT_CHRONOBOOSTENERGYCOST, nexus))

**Comment by ryanmccauley211** [comment]
This worked for me, thanks.

**Comment by Dentosal** [comment]
Closing as fixed.
