### ISSUE TITLE
How to trigger research

### ISSUE THREAD

**Issue by GamerNato** [Dentosal/python-sc2#84]
been having some trouble with research as i cant figure out how to trigger it properly without the "is not defined" error

i've looked through the files and found that the propper name is 'PROTOSSAIRWEAPONSLEVEL1' but that hasn't worked

i've also tried various other methods of doing this but none of them seem to work properly

below is my latest attempt

    async def research(self):
        for csc in self.units(CYBERNETICSCORE).ready:
            if self.minerals >= 100 and self.vespene >= 100 and not self.PAW_started:
                await self.do(csc(RESEARCH_AIRWEAPONSLEVEL1))
                self.PAW_started = True

**Comment by mjschuetze102** [comment]
```
if self.units(UnitTypeId.EVOLUTIONCHAMBER).ready.exists:
    building = self.units(UnitTypeId.EVOLUTIONCHAMBER).ready.first
    abilities = await self.get_available_abilities(building)
    if AbilityId.RESEARCH_ZERGMELEEWEAPONSLEVEL1 in abilities:
        if self.can_afford(AbilityId.RESEARCH_ZERGMELEEWEAPONSLEVEL1) and building.noqueue:
            await self.do(building(AbilityId.RESEARCH_ZERGMELEEWEAPONSLEVEL1))
```

This is what I did for when I was trying to upgrade... 

Also, in your example above, I noticed you have RESEACH_AIRWEAPONSLEVEL1 instead of CYBERNETICSCORERESEARCH_PROTOSSAIRWEAPONSLEVEL1. That could be your issue. If you look in sc2.ids.upgrade_id.py, you will find a list of abilities that can be used. It's just a matter of finding the one that suits your needs

**Comment by BurnySc2** [comment]
I suppose that solved it. :)
Also see #33

**Comment by BryceWayne** [comment]
I am having the same issue.

```
async def research(self):
	building = self.units(SPAWNINGPOOL).ready
	for b in building:
		if self.can_afford(RESEARCH_ZERGLINGMETABOLICBOOST):
			await self.do(building(RESEARCH_ZERGLINGMETABOLICBOOST))
```

The error is,
```
Traceback (most recent call last):
  File "C:\Users\Algrus\Anaconda3\lib\site-packages\sc2\main.py", line 150, in _play_game_ai
    await ai.on_step(iteration)
  File "C:\Users\Algrus\Documents\Programs\StarCraft2Bot\sc2bot.py", line 26, in on_step
    await self.research()
  File "C:\Users\Algrus\Documents\Programs\StarCraft2Bot\sc2bot.py", line 97, in research
    await self.do(building(RESEARCH_ZERGLINGMETABOLICBOOST))
  File "C:\Users\Algrus\Anaconda3\lib\site-packages\sc2\units.py", line 47, in __call__
    return UnitSelection(self, *args, **kwargs)
  File "C:\Users\Algrus\Anaconda3\lib\site-packages\sc2\units.py", line 360, in __init__
    ), f"selection is not None or of type UnitTypeId or Set[UnitTypeId]"
AssertionError: selection is not None or of type UnitTypeId or Set[UnitTypeId]
```
