### ISSUE TITLE
PyPi and github report different latest versions

### ISSUE THREAD

**Issue by Unclevinny** [Dentosal/python-sc2#93]
Maybe not a bug, exactly, but:
https://pypi.org/project/sc2/0.8.4/#history
Says 0.8.4 is the latest, but doesn't give a commit marker.

https://github.com/Dentosal/python-sc2/releases
Says 0.8.3 is the latest, points to https://github.com/Dentosal/python-sc2/commit/7d889967be39a874a7d882af1c999a111d86c8c2

Should github automatically report new releases, or does it require a manual step by the developer?

**Comment by BurnySc2** [comment]
It is done manually pushed to pip by Dentosal.

Slightly unrelated:
You can use 
`pip install git+https://github.com/Dentosal/python-sc2.git`
to install the latest version on github.

**Comment by BurnySc2** [comment]
Closing this as pip and github-releases now have the same version.
