### ISSUE TITLE
expand.now() method problem

### ISSUE THREAD

**Issue by Matuiss2** [Dentosal/python-sc2#97]
It throws an error when there is a lair ready(tested the same code that threw an error but without the lair upgrade and it worked) here is the traceback
```
Traceback (most recent call last):
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sc2\main.py", line 60, in _play_game_ai
    await ai.on_step(iteration)
  File "C:/Users/Pichau/PycharmProjects/sc2 bot/Zerg_roach_hydra.py", line 32, in on_step
    await self.build_hatchery()
  File "C:/Users/Pichau/PycharmProjects/sc2 bot/Zerg_roach_hydra.py", line 82, in build_hatchery
    await self.expand_now()
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sc2\bot_ai.py", line 100, in expand_now
    placement_step=1)
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sc2\bot_ai.py", line 307, in build
    p = await self.find_placement(building, near.rounded, max_distance, random_alternative, placement_step)
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sc2\bot_ai.py", line 243, in find_placement
    assert self.can_afford(building)
AssertionError
```

**Comment by alexander-kazakov** [comment]
Same happens when you play Terran and have an ORBITAL COMMAND

**Comment by mjschuetze102** [comment]
I was receiving this error before upgrading to a lair (but I had 8 hatcheries). My guess was that too much time was passing between when I was checking if I could to expand vs when it was checking, allowing for another building/unit to use up those resources.

**Comment by mjschuetze102** [comment]
This essentially has the same effect of taking out the assert statement from the expand_now() method. Which is completely fine since I don't really understand why the assert message is there to begin with, since the game yells at you for not having enough minerals anyway.

The only way to effectively combat this would be to "lock" the resources by getting the total amount at each game loop and storing that in a _synchronized_ method. Each can_afford() method would have to call the synchronized one and subtract the requested amount from the total collected earlier. Then you would have a real count of your mineral/gas total at any given time, including the cost of buildings a worker is heading over to produce.

**Comment by BurnySc2** [comment]
Well, the assert statement is only in the `self.find_placement()` function
https://github.com/Dentosal/python-sc2/blob/efb7e52745cc9f5aea1055b64ec6b25ac4ac13b3/sc2/bot_ai.py#L284
and the `self.do()` function
https://github.com/Dentosal/python-sc2/blob/efb7e52745cc9f5aea1055b64ec6b25ac4ac13b3/sc2/bot_ai.py#L358

The `self.expand_now()` function doesn't even have an assert.
I guess I could remove the assert in the `self.find_placement()` but I'd rather leave it in the `self.do()` function. Even after the change, the `self.expand_now()` function would still return an assert error.

I think what you are trying to describe is already implemented by Dentosal
https://github.com/Dentosal/python-sc2/blob/efb7e52745cc9f5aea1055b64ec6b25ac4ac13b3/sc2/bot_ai.py#L357-L364
The `self.do()` function already reduces minerals and vespene accordingly from the player's bank. Of course that value is restored in the next game loop.

**Comment by ByBurton** [comment]
Having a similar problem. My script crashes whenever I try to take the 2nd expansion. Is it because of my lair / hive? Please. help me. Or is it an error I made (have an open issue here)

**Comment by ByBurton** [comment]
So I tested around a bit more, and it does not seem to be the resources. Because I clearly have them. But I do not have any regular hatcheries anymore. Only hives and lairs. Maybe that can be a problem?

**Comment by BurnySc2** [comment]
It should be fixed now and on master branch. If you still encounter issues, feel free to reopen this issue.
